name = "lifegrid"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install"

# Enable WASM modules
rules = [
  { type = "CompiledWasm", globs = ["**/*.wasm"] }
]

# Uncomment to add custom domain
# [[routes]]
# pattern = "life-calendar.yourdomain.com/*"
# zone_name = "yourdomain.com"
